### PR TITLE
css for view profil

### PR DESCRIPTION
**Pull request by Bruno-Fernandes-37**

### CODE REVIEW

**Review by CECDO — DISMISSED** [review]
ok

**Review by ghost — DISMISSED** [review]
ok

**Review by ghost — DISMISSED** [review]
ok

**Review by sebastien-violante — COMMENTED** [review]
One blank line should be deleted in /_profil.scss

**Review by CECDO — DISMISSED** [review]
ok

**Review by sebastien-violante — CHANGES_REQUESTED** [review]
See my comment : _profile.scss line 10 is blank

**Review by sebastien-violante — APPROVED** [review]

**Review by RomainClair — APPROVED** [review]

**Pull request merged**
